### PR TITLE
Adds more cities to server-locations.json and changes tint color setting method

### PR DESCRIPTION
**Pull request by natanrolnik**
More South American and Israeli cities

### CODE REVIEW

**Comment by natanrolnik** [comment]
@MosheBerman can you merge and update please?

**Comment by MosheBerman** [comment]
"We can't automatically merge this pull request." I'm not sure why. Do you know what the conflict is?

**Comment by natanrolnik** [comment]
I have no idea - shouldn't be. Initially that was only the json file. There shouldn't be conflicts.

**Comment by MosheBerman** [comment]
I'll get on it.

**Comment by MosheBerman** [comment]
Merged, thanks!

**Pull request merged**
